name: RFC
description: Create an RFC
title: "[RFC]: "
labels: ["RFC"]
projects: ["axleus/TSC"]
body:
  - type: input
    id: version
    attributes:
      label: Proposed Version
      description: Which version of the component does this target or is it a new Major/Minor?
      placeholder: 0.0.1
    validations:
      required: true
  - type: markdown
    id: basic
    attributes:
      value: |
        What does this RFC propose?
  - type: markdown
    id: background
    attributes:
      value: |
        Background information that led to this RFC.
  - type: markdown
    id: considerations
    attributes:
      value: |
        How does this affect users, related packages etc.
  - type: markdown
    id: proposal
    attributes:
      value: |
        How do we accomplish it?
  - type: markdown
    id: appendix
    attributes:
      value: |
        Add any references, RFCs or other information which may be useful.
